# NOTE: update this with your service name
service: rfx-webapp-cp-api-transfers

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  secrets: ${file(secrets.json)}
  customDomain:
    domainName: 'webcp-api.remitfx.io' # Change this to your domain.
    basePath: 'transfers' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  profile: ctin
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    SERVICE_NAME: ${self:service}

functions:
  # ==========================================
  # TRANSFERS API
  # ==========================================
  transfers_get_all:
    handler: src/get.all
    events:
      - http:
          path: get-all
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_list_not_deleted:
    handler: src/get.list_not_deleted
    events:
      - http:
          path: get-list-not-deleted
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_by_id:
    handler: src/get.by_id
    events:
      - http:
          path: get/id/{id}
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_by_team_id:
    handler: src/get.by_team_id
    events:
      - http:
          path: getByTeam/id/{id}
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_list_summary:
    handler: src/get.list_summary
    events:
      - http:
          path: get-list-summary/id/{id}
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_full_by_id:
    handler: src/get.full_by_id
    events:
      - http:
          path: get-full/id/{id}
          method: get
          cors: true
          authorizer: aws_iam
  transfers_get_transfer_status:
    handler: src/get.transfer_status
    events:
      - http:
          path: get/transfer-status
          method: get
          cors: true
          authorizer: aws_iam
  transfers_update_by_id:
    handler: src/update.by_id
    events:
      - http:
          path: update/id/{id}
          method: put
          cors: true
          authorizer: aws_iam
  transfers_create_in_database:
    handler: src/create.in_database
    events:
      - http:
          path: create/in-database
          method: post
          cors: true
          authorizer: aws_iam

  transfers_get_remitting_account:
    handler: src/remitting_account.get_details
    events:
      - http:
          path: remitting-account/get-details
          method: post
          cors: true
          authorizer: aws_iam

  transfers_get_purpose:
    handler: src/get.get_purpose
    events:
      - http:
          path: get_purpose/id/{division_id}
          method: get
          cors: true
          authorizer: aws_iam