# NOTE: update this with your service name
service: rfx-webapp-cp-api-currencies

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  secrets: ${file(secrets.json)}
  customDomain:
    domainName: 'webcp-api.remitfx.io' # Change this to your domain.
    basePath: 'currencies' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  profile: ctin
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    SERVICE_NAME: ${self:service}

functions:
  # --------------
  # Currencies API
  # --------------
  currencies_get_all:
    handler: src/get.all
    events:
      - http:
          path: currencies/get-all
          method: get
          cors: true
          authorizer: aws_iam
  currencies_get_all_priority:
    handler: src/get.all_priority
    events:
      - http:
          path: currencies/get-all-priority
          method: get
          cors: true
          authorizer: aws_iam
  currencies_get_all_not_deleted:
    handler: src/get.list_not_deleted
    events:
      - http:
          path: currencies/get-not-deleted
          method: get
          cors: true
          authorizer: aws_iam
  currencies_get:
    handler: src/get.id
    events:
      - http:
          path: currencies/get/{currency_id}
          method: get
          cors: true
          authorizer: aws_iam
  currencies_create_in_database:
    handler: src/create.in_database
    events:
      - http:
          path: currencies/create/in-database
          method: post
          cors: true
          authorizer: aws_iam
  currencies_update:
    handler: src/update.id
    events:
      - http:
          path: currencies/update/id/{currency_id}
          method: put
          cors: true
          authorizer: aws_iam
    currencies_delete:
      handler: src/delete.id
      events:
        - http:
            path: currencies/delete/currency_id/{currency_id}
            method: put
            cors: true
            authorizer: aws_iam