# NOTE: update this with your service name
service: rfx-webapp-cp-api-identification

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  secrets: ${file(secrets.json)}
  customDomain:
    domainName: 'webcp-api.remitfx.io' # Change this to your domain.
    basePath: 'identification' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  profile: ctin
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    SERVICE_NAME: ${self:service}

functions:
  create_test:
    handler: src/create.test
    events:
      - http:
          path: create/test
          method: post
          cors: true
          authorizer: aws_iam
  get_by_client_id:
    handler: src/get.by_client_id
    events:
      - http:
          path: get/client_id/{client_id}
          method: get
          cors: true
          authorizer: aws_iam

  get_all:
    handler: src/get.all
    events:
      - http:
          path: get/all
          method: get
          cors: true
          authorizer: aws_iam

  get_ident_categories:
    handler: src/get.categories
    events:
      - http:
          path: get/categories
          method: get
          cors: true
          authorizer: aws_iam

  create_in_database:
    handler: src/create.in_database
    events:
      - http:
          path: create/in-database
          method: post
          cors: true
          authorizer: aws_iam
  get_by_id:
    handler: src/get.by_id
    events:
      - http:
          path: get/id/{id}
          method: get
          cors: true
          authorizer: aws_iam
  get_ident_status:
    handler: src/get.identification_status
    events:
      - http:
          path: get/identification_status/
          method: get
          cors: true
          authorizer: aws_iam
  update_by_id:
    handler: src/update.by_id
    events:
      - http:
          path: update/id/{id}
          method: put
          cors: true
          authorizer: aws_iam
  get_list_not_deleted:
    handler: src/get.list_not_deleted
    events:
      - http:
          path: get/list_not_deleted
          method: get
          cors: true
          authorizer: aws_iam